### PR TITLE
Upgrade Undici to v6.7.0

### LINKED ISSUE #82: Support Undici v6
## 🚀 Feature Proposal

The library currently constrains undici to `^5.22.1`. Undici v6 has been out since almost 2 months, `@elastic/transport` should support it. I don't think big breaking changes have been brought, expect that Node 16, which [has reached EOL](https://endoflife.date/nodejs), is not supported anymore ([PR](https://github.com/nodejs/undici/pull/2480)).

## Motivation

Keep up with security fixes, bug fixes, performance improvements, ...

### PR DESCRIPTION
**Pull request by cosieLq**
Closes #82 

This PR tries to upgrade Undici to v6.7.0. I haven't run integration tests, and I'm curious if everything is still working well.

This is my first commit to this repo, and comments are very welcome! :relaxed:

### CODE REVIEW

**Comment by thomasconner** [comment]
Any update on this?

**Comment by JoshMock** [comment]
Finally got a chance to pull this down and test it against the client. All unit and integration tests pass smoothly! Just need @cosieLq to sign that CLA and I can merge this for the next minor release.

**Comment by JoshMock** [comment]
@cosieLq Additionally, if you merge main into this branch, those Node 16 tests will be removed.

**Comment by cosieLq** [comment]
> @cosieLq Additionally, if you merge main into this branch, those Node 16 tests will be removed.

I've signed the CLA and merged main to this branch. Thank you for your reviewing and testing!

**Review by JoshMock — APPROVED** [review]

**Pull request merged**
