### PR TITLE
Fix MaxListenersExceededWarnings

### PR DESCRIPTION
**Pull request by skarahoda**
Using the connection's emitter for undici's request causes a memory leak. In this PR, a local abort signal is used to fix the issue.

Related Issues:
https://github.com/elastic/elasticsearch-js/issues/1741
https://github.com/elastic/elasticsearch-js/issues/1733
https://github.com/elastic/elasticsearch-js/issues/1716

### CODE REVIEW

**Comment by phil-nelson-bt** [comment]
We are getting this error (warning) from EventEmitter shortly after every time a k8s pod starts. Our current client / server version is 7.17 but I tried with the 8.6 client too. With 8.6 the message changes a little in the stack trace, but the result is still another log in our error logs

```
(node:91202) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 abort listeners added to [EventEmitter]. Use emitter.setMaxListeners() to increase limit
    at _addListener (node:events:587:17)
    at EventEmitter.addListener (node:events:605:10)
    at addSignal (/Users/philnelson/Projects/productivitysuiteservice/node_modules/undici/lib/api/abort-signal.js:35:19)
    at new RequestHandler (/Users/philnelson/Projects/productivitysuiteservice/node_modules/undici/lib/api/api-request.js:63:5)
    at Pool.request (/Users/philnelson/Projects/productivitysuiteservice/node_modules/undici/lib/api/api-request.js:193:25)
    at /Users/philnelson/Projects/productivitysuiteservice/node_modules/undici/lib/api/api-request.js:186:15
    at new Promise (<anonymous>)
    at Pool.request (/Users/philnelson/Projects/productivitysuiteservice/node_modules/undici/lib/api/api-request.js:185:12)
    at Connection.request (/Users/philnelson/Projects/productivitysuiteservice/node_modules/@elastic/transport/lib/connection/UndiciConnection.js:143
    ```

**Comment by madispuk** [comment]
Any updates when this fix will be merged in? We are also running into this issue.

**Comment by GuillaumeCisco** [comment]
Why closing it? Has it been fixed in another PR?

**Comment by ahmedsamir-dev** [comment]
@skarahoda 
I just want to inquire has it been fixed ?

**Comment by JoshMock** [comment]
I'm taking over as the maintainer of this repo and getting familiar with it. Hoping to be able to address this issue soon. I'll track progress in #63.

**Pull request closed without merging**
